### PR TITLE
Add gather command by tags

### PR DESCRIPTION
**Pull request by AlyssaPng**
Add gather command by tags for enhancement

### CODE REVIEW

**Review by sopa301 — COMMENTED** [review]
I think it's quite a good idea to use a Command Pattern to implement the gather command. Nice work!

As a side note, perhaps it would be more readable to rename GatherEmails to a noun instead of a verb like GatherEmailPrompt or something since it would make it easier to reason about, as well as being more intuitive for first-timers.

Also, putting these into a separate folder would make the file structure more neat too.

**Review by Kb-Tay — COMMENTED** [review]
Implementation wise LGTM. However, can consider the following suggestions made. Can also include more testing for invalid command inputs.

**Review by nikele2001 — COMMENTED** [review]
lgtm

**Review by sopa301 — APPROVED** [review]
LGTM

**Pull request merged**
